name: Generate Snake Dark

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: devix05
          output: dist/snake.svg

      - name: Move Snake to Root
        run: mv dist/snake.svg snake.svg

      - name: Check generated files
        run: ls -l

      - name: Commit and push Snake
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add snake.svg
          git commit -m "Update snake.svg" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
