name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # alle 12 Stunden
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: devix05
          output: snake.svg   # direkt im Root

      - name: Commit & push snake.svg
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add snake.svg
          git commit -m "Update snake.svg" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
